# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180921_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 11, 30, 40, 581080, tzinfo=utc), verbose_name=datetime.datetime(2018, 9, 21, 11, 30, 35, 247878, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
